---
# tasks file for ansible-macterm

- name: '[main] Determine brew prefix'
  ansible.builtin.command: 'brew --prefix'
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  register: macterm_brew_prefix
  changed_when: false
  tags: macterm

- name: '[main] Import Terminal app tasks'
  ansible.builtin.import_tasks:
    file: terminal_app.yml
  tags: macterm

- name: '[main] Include iTerm2 tasks'
  ansible.builtin.include_tasks:
    file: iterm2.yml
    apply:
      tags:
        - macterm
        - macterm_iterm2
  when: macterm_iterm2
  tags:
    - macterm
    - macterm_iterm2

- name: '[main] Include Fingerprint sensor tasks'
  ansible.builtin.include_tasks:
    file: fingerprint_sensor.yml
    apply:
      tags:
        - macterm
        - macterm_fingerprint
  when: macterm_fingerprint_sensor
  tags:
    - macterm
    - macterm_fingerprint

- name: '[main] Flush all handlers'
  ansible.builtin.meta: flush_handlers
  tags:
    - macterm
    - macterm_iterm2
    - macterm_fingerprint
