---
- name: "[macdock_look] Ensure dockutil is installed"
  # temporary solution to https://github.com/kcrawford/dockutil/issues/127
  # This should not be cask in the future and should not require password
  community.general.homebrew_cask:
    name: hpedrorodrigues/tools/dockutil
    state: present
    sudo_password: "{{ macdock_become_pass|default(omit) }}"
  register: macdock_dockutils_result
  until: macdock_dockutils_result is successful

- name: "[macdock_look] Remove all dock items"
  ansible.builtin.command: "/usr/local/bin/dockutil --remove all --no-restart"

- name: "[macdock_look] Add items to dock"
  ansible.builtin.command: >
    /usr/local/bin/dockutil \
      --add '{{ item.path }}' \
      --position {{ item.pos }} \
      --section {{ item.section | default('apps') }} \
      --no-restart
  with_items: "{{ macdock_add_items }}"
  notify: Restart Dock
